### ISSUE TITLE
stereo sound

### ISSUE THREAD

**Issue by msx-solis** [vipoo/rc2014-game#1]
Hi,
Even most MSX didn't had stereo sound you can easily implement this looking at what was done for the ECB SBC computer, you can take some information from the Sprites Colors Graphics and Sound card.
https://www.retrobrewcomputers.org/doku.php?id=boards:ecb:scg:start
This system also has IDE disk systems.
I have MSX cartridge designs for IDE or Compact flash too.

I hope this helps
I've never had an RC2014 system but I will consider having one if I can buy (or manufacture) the bare boards.
kind regards.

**Comment by vipoo** [comment]
Hello,

Thanks for the link - there are so many wonderful homebrew systems to take inspiration and design ideas from - there is no way i could have designed the boards i have done, without these published systems.

I have a working HDD and Floppy Drive interface working for my RC2014 - under CP/M.  When time permits, i wish to port the drivers over to MSX-DOS - I am hoping there are no IO port conflicts.

Not sure if you are aware, but you can buy bare boards from Spencer Owens tindie store (https://www.tindie.com/stores/semachthemonkey/items/).  You can also checkout his website for the platform - https://rc2014.co.uk/ - this describes the various versions of cpus/backplanes etc.

_Also please note - I have moved this repo to https://github.com/vipoo/yellow-msx-series-for-rc2014 - so will be archiving this repo shortly._
